[workspace]
resolver = "2"

members = [
    "sig"
]

[patch.crates-io]
ark-r1cs-std = { path = "./third_party/r1cs-std" }
ark-crypto-primitives = { path = "./third_party/crypto-primitives/crypto-primitives" }
