[package]
name = "sig"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.5.0"
ark-crypto-primitives = {version = "0.5.0", features = ["crh"]}
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-r1cs-std = "0.5.0"
ark-relations = "0.5.1"
ark-std = "0.5.0"
blake2 = "0.10.6"
rand = "0.8.5"
